AllCops:
  Exclude:
    - 'devise-4.5.0/**/*'
    - 'Gemfile.lock'
    - 'config/**/*'
    - 'bin/**/*'

Documentation:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
