language: 
 — ruby
rvm:
 — 2.5.0
cache:
 — bundler
script:
 — bundle install
 — bin/rails db:create
 — bin/rails db:migrate
 — bundle exec rspec
services:
 — postgresql
# deployment details - add while setting up Heroku 
deploy:
  provider: heroku
 api_key:
  secure: 
app: polar-scrubland-14593
  on:
 repo: https://github.com/michaelnguyen974/acebook-Justice_Moo
